server:
  port: 8082
mydocument:
  service:
    storage:
      serviceEndPoint: http://localhost:8081/storage
  aws:
    s3:
      serviceEndpoint: https://s3.amazonaws.com
      signingRegion: us-east-1
      systemBucket: docbankrepositorysystem
      catModelFile: doc_cat_model2.bin
    textract:
      serviceEndpoint: https://textract.us-east-1.amazonaws.com
      signingRegion: us-east-1
    dynamodb:
      serviceEndPoint: dynamodb.us-east-1.amazonaws.com
      signingRegion: us-east-1
  mq:
    upload:
      topicExchangeName: myDocumentUploadExchange
      queueName: myDocumentUploadQuque
      routingKey: mydocument.upload.key
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 15s
