server:
  port: 8081
mydocument:
  aws:
    s3:
      serviceEndpoint: https://s3.amazonaws.com
      signingRegion: us-east-1
      systemBucket: docbankrepositorysystem
      catModelFile: doc_cat_model2.bin
  mq:
    upload:
      topicExchangeName: myDocumentUploadExchange
      queueName: myDocumentUploadQuque
      routingKey: mydocument.upload.key
spring:
  rabbitmq:
    host: mydocument-mq-broker
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 15s