server:
  port: 8081
mydocument:
  aws:
    s3:
      serviceEndpoint: https://s3.amazonaws.com
      signingRegion: us-east-1
      systemBucket: docbankrepositorysystem
      catModelFile: doc_cat_model2.bin
  mq:
    upload:
      topicExchangeName: myDocumentUploadExchange
      queueName: myDocumentUploadQuque
      routingKey: mydocument.upload.key
spring:
  rabbitmq:
    host: mydocument-mq-broker
#    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 15s
  datasource:
    username: ${POSTGRES_USER_STORAGEDB}
    password: ${POSTGRES_PASS_STORAGEDB}
    url: jdbc:postgresql://mydocument-storage-db:5432/mydocument_storage_db
#    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 5000 #ms
      maximum-pool-size: 20
      pool-name: mydocument-storage-db-pool
#      pool-name: polardb-catalog-pool
  jpa:
    hibernate.ddl-auto: create-drop