version: "3.8"
services:
  mydocument-mq-broker:
    image: "rabbitmq:3-management"
    container_name: "mydocument-mq-broker"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  storage-service:
    image: "chungha/storageservice"
    container_name: "storage-service"
    ports:
      - 8081:8081
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POSTGRES_USER_STORAGEDB=${POSTGRES_USER_STORAGEDB}
      - POSTGRES_PASS_STORAGEDB=${POSTGRES_PASS_STORAGEDB}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mydocument-storage-db:5432/mydocument_storage_db
  parsing-service:
    image: "chungha/parsingservice"
    container_name: "parsing-service"
    ports:
      - 8082:8082
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POSTGRES_USER_STORAGEDB=${POSTGRES_USER_STORAGEDB}
      - POSTGRES_PASS_STORAGEDB=${POSTGRES_PASS_STORAGEDB}
      - MYDOCUMENT_SERVICE_STORAGE_SERVICEENDPOINT=${MYDOCUMENT_SERVICE_STORAGE_SERVICEENDPOINT}
  mydocument-storage-db:
    image: "postgres:13"
    container_name: "mydocument-storage-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_STORAGEDB}
      - POSTGRES_PASSWORD=${POSTGRES_PASS_STORAGEDB}
      - POSTGRES_DB=mydocument_storage_db
      
  