spring:
  cloud:
    function:
      definition: trainautocat
    stream:
      bindings:
        trainautocat-in-0:
          destination: parse-completed
          group: parse-autocat
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 15s
